function showTheBookData(e){
  e.preventDefault();
  console.log(hobby);
  $.ajax({
    type: 'POST',
    url:"https://cse120-2021api-anisahak.herokuapp.com/data",
    data: hobby,
    cache: false,
    dataType : 'json',
    success: function (data) {
      console.log("success");
    },
    error: function (xhr) {
      console.error("Error in post", xhr);
    },
    complete: function () {
      console.log("Complete");  
    }
  });
}

function loadExistingData() {
	var existingData = [];
  $.ajax({
    type : "GET",
    url : "https://cse120-2021api-anisahak.herokuapp.com/data",
    dataType : "json",
    success : function(data) {
      console.log("success", data);
      existingData = data;
      displayData(existingData.data);
    },
    error : function(data) {
        console.log("Error")
    }
  })
}

function displayData(data) {
    document.getElementById("perfumeDataContainer").innerHTML = "";
    data.forEach(elem => {

    var item = document.createElement("div");
        item.id = "div" + elem["_id"];
        item.className = "item";
    if (Object.keys(elem).length == 1) {
    var span = document.createElement("span");
        span.innerHTML = "<i>Empty Element with autogenerated ID: </i>" + elem["_id"];
        item.appendChild(span);
        }
    Object.keys(elem).forEach(key => {
      if (key != "_id") {
      var span = document.createElement("span");

      var b = document.createElement("b");
          b.innerHTML = key + ": ";
          span.appendChild(b);
                
          span.className = "item";
      if (elem[key]) {
          span.innerHTML += elem[key];
      } else {
        
      var span1 = document.createElement("span");
          span1.className = "undefined";
          span1.innerHTML = "N/A";
          span.appendChild(span1)
                }
          item.appendChild(span);

      var br = document.createElement("br");
          item.appendChild(br);
            }
        })
      var button = document.createElement("button");
        button.innerHTML = "Delete";
        button.id = elem["_id"];
        button.addEventListener("click", function(e){
          deleteData(e.target.id);
        }, false);
        item.appendChild(button);
        document.getElementById("perfumeDataContainer").appendChild(item);
    })

}
var loadedData = [];
  


var hobby = {
  "name" : "Ani",
  "lastname": "Sahakyan",
  "duration": "",
  "reason": "",
  "Favfragrance": "",
  "Brand": "",
  "type": "",
  "attribute1": false,
  "attribute2": false,
  "attribute3": false,
  "attribute4": false,
  "Preference": "",
  "fragrance": "",
  "otherPreference": "",
  "collection": "",
  "othercollection": "",
  "FavoritePerfumes": "",
  "Add":"",
}

function printdurationvalue() {
   hobby.duration = document.getElementById("duration").value;
}

function printreasonvalue() {
  hobby.reason = document.getElementById("reason").value;
}

function printFavfragrancevalue() {
  hobby.Favfragrance = document.getElementById("Favfragrance").value;
}

function printBrandvalue() {
  hobby.Brand = document.getElementById("Brand").value;
}

function printcovertypevalue(e){
 hobby.covertype= e.target.value; 
 if (hobby.covertype !="other"){
   hobby.other="";
   document.getElementById("othertext").style.display="none";
 } else{
   document.getElementById("othertext").style.display="block";
 }
}

function printothervalue(){
  if(hobby.covertype="other"){
    hobby.other=document.getElementById("othertext").value;
  }
}

function printotherlanguagevalue(){
if(hobby.language="other1"){
 hobby.otherlanguage=document.getElementById("othertext1").value;
}
}

function printoriginallanguagevalue(e){
 hobby.originallanguage= e.target.value; 
 if (hobby.originallanguage !="other2"){
   hobby.otherlanguage2="";
   document.getElementById("othertext2").style.display="none";
 } else{
   document.getElementById("othertext2").style.display="block";
 }
}

function printotherlanguagevalue2(){
  if(hobby.originallanguage==="other2"){
    hobby.otherlanguage2=document.getElementById("othertext2").value;
  }
}


function printFavoritePerfumesvalue() {
  hobby.FavoritePerfumes = document.getElementById("FavoritePerfumes").value; 
}  

function printAddvalue() {
  hobby.Add = document.getElementById("Add").value; 
}  

function printtypevalue(e) {
 hobby.type= e.target.value;
}

function printPreferencevalue(e){
  if(e.target.value === "Other"){
    document.getElementById('otherPreference').disabled = false;
  }else{
    hobby.Preference= e.target.value;
  }
}

function printcollectionvalue(e){
  if(e.target.value === "other"){
    document.getElementById('othercollection').disabled = false;
  }else{
    hobby.fragrance= e.target.value;
  }
}

function fragranceOtherChange(e){
  hobby.Preference= document.getElementById('othercollection').value;
}

function preferenceOtherChange(e){
  hobby.Preference= document.getElementById('otherPreference').value;
}

function printAttributes1Value(e){
  hobby.attribute1 = document.getElementById('attribute1').checked;
}

function printAttributes2Value(e){
  hobby.attribute2 = document.getElementById('attribute2').checked;
}

function printAttributes3Value(e){
  hobby.attribute3 = document.getElementById('attribute3').checked;
}

function printAttributes4Value(e){
  hobby.attribute4 = document.getElementById('attribute4').checked;
}
 
function SaveData(){
  console.log(hobby)
}